name: edu_student
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  audio_session: ^0.1.18
  animations: ^2.0.8
  animated_text_kit: ^4.2.3
  animate_do: ^4.2.0
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  camerawesome: ^2.0.1
  cupertino_icons: ^1.0.8
  custom_timer: ^0.2.3

  dio: ^5.2.1+1
  dropdown_button2: ^2.3.9
  device_info_plus: ^11.4.0

  equatable: ^2.0.7
  # ed_screen_recorder: ^0.0.15
  
  flutter_bloc: ^9.1.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.4.0
  flow_builder: ^0.0.10
  flutter_downloader: ^1.10.4
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.10+1

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_sound: ^9.2.13

  googledrivehandler: ^1.0.5
  
  intl: ^0.20.2
  image_picker: ^1.0.8
  image_gallery_saver_plus: ^4.0.1

  gal: ^2.2.0
  
  get_it: ^8.0.3

  lottie: ^2.7.0

  loading_animation_widget: ^1.3.0

  http: ^1.1.0
  object_mapper: ^1.2.1
  open_filex: ^4.4.0

  stream_transform: ^2.1.1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.1
  redacted: ^1.0.12
  permission_handler: ^11.0.0
  path: ^1.8.3
  path_provider: ^2.0.10

  url_launcher: ^6.2.4
  uuid: ^3.0.7
  video_player: ^2.1.4

  webview_flutter: ^4.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/trenet.png
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
      - assets/logo.png
      - assets/logo.png
      - assets/user.png
      - assets/menu5.jpg
      - assets/image-icon.png
      - assets/trenet.png
      - assets/teacher.png
      - assets/student.png

